http://localhost:8080/user/art
###
http://localhost:8080/testing?name=Pasut&address=TheTrust
###
curl -v -X GET http://localhost:8080/someDataFromReader
###
curl -kIL https://raw.githubusercontent.com/gin-gonic/logo/master/color.png